### ISSUE TITLE
publish to Open VSX registry

### ISSUE THREAD

**Issue by marc0olo** [mradkov/vscode-sophia#8]
Hey @mradkov, would you mind adding the Sophia extension to the Open VSX registry? https://open-vsx.org/

any suggestion how to proceed if I wanna see it published there? :-)

**Comment by marc0olo** [comment]
any chance you tackle that one @mradkov ? :-) just thought about this topic again 😅

**Comment by mradkov** [comment]
Hey @marc0olo, the extension is published to open-vsx under the `hackbg` namespace.

```
🚀  Published hackbg.sophia v2.1.0
```

**Comment by marc0olo** [comment]
very cool! thanks @mradkov <3
